### ISSUE TITLE
recall the values in the front end

### ISSUE THREAD

**Issue by Nickyg001** [boospot/boo-settings-helper#2] opened 2021-02-25 15:37 UTC
Once the various fields have been implemented for a Helper class, let's say for example that it inserts text fields, or radio buttons, or media, how can I recall these values inserted in the backend in this options page in the front-end?

example with ACF there is the: <? php the_field ('FIELD_NAME'); ?>

**Comment by boospot** [comment] 2021-02-25 15:46
Hi Nickyg001,

You call the value like a regular WordPress option using the function `get_option()`
https://developer.wordpress.org/reference/functions/get_option/

If you are using prefix, then add the prefix with option key, otherwise, simply use the `id` of field array to use as `option` for `get_option()` function

**Comment by raoabid** [comment] 2021-07-09 06:53
Looks like the issue is solved for you.
Closing this for now.

**Closed as completed by raoabid** 2021-07-09 06:53 UTC
